name: shamil_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  bloc: ^9.0.0
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.5.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  collection: ^1.19.1
  country_code_picker: ^3.2.0
  cupertino_icons: ^1.0.2
  device_calendar: ^4.3.3
  dots_indicator: ^4.0.1
  equatable: ^2.0.5
  firebase_app_check: ^0.3.2+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.1.0
  provider: ^6.1.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^14.0.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_document_scanner: ^0.2.1
  google_mlkit_barcode_scanning: ^0.11.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  line_icons: ^2.0.3
  lottie: ^3.3.1
  nfc_manager: ^4.0.2
  onesignal_flutter: ^5.3.2
  permission_handler: ^12.0.0+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  timezone: ^0.9.4
  url_launcher: ^6.2.1
  uuid: ^4.3.3
  google_sign_in: ^6.1.6
  share_plus: ^11.0.0
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.4.0
  local_auth: ^2.1.6
  flutter_local_notifications: ^18.0.1
  # workmanager: ^0.5.2  # Removed due to Kotlin compilation issues
  crypto: ^3.0.3
  http: ^1.1.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  get_it: ^8.0.3
  injectable: ^2.3.2
  logger: ^2.0.2+1
  rxdart: ^0.28.0
  encrypt: ^5.0.1
  pointycastle: ^3.7.3
  sentry_flutter: ^8.14.2
  firebase_analytics: ^11.3.4
  firebase_crashlytics: ^4.1.4
  # Payment dependencies
  webview_flutter: ^4.4.2
  flutter_stripe: ^10.1.1
  in_app_purchase: ^3.1.13
  flutter_secure_storage: ^9.0.0
  # Sensor dependencies for gyroscope integration
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: ^5.4.2
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
    - assets/images/
  fonts:
    - family: BalooBhaijaan2
      fonts:
        - asset: assets/fonts/BalooBhaijaan2-Regular.ttf
          weight: 400
        - asset: assets/fonts/BalooBhaijaan2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooBhaijaan2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BalooBhaijaan2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooBhaijaan2-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# Flutter launcher icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/AppIcon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/AppIcon.png"
    background_color: "#ffffff"
    theme_color: "#20c997"
  windows:
    generate: true
    image_path: "assets/images/AppIcon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/AppIcon.png"
  adaptive_icon_background: "#20c997"
  adaptive_icon_foreground: "assets/images/AppIcon.png"
