name: shamil_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animations: ^2.0.11
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  card_swiper: ^3.0.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.5
  cloud_functions: ^5.5.0
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  collection: ^1.19.1
  country_code_picker: ^3.2.0
  cupertino_icons: ^1.0.8
  dots_indicator: ^4.0.1
  equatable: ^2.0.7
  firebase_app_check: ^0.3.2+4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.5
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  intl: ^0.20.2
  line_icons: ^2.0.3
  lottie: ^3.1.2
  nfc_manager: ^3.5.0
  permission_handler: ^11.4.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
