// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLiw9qjIa5tlob_sPSgXBKk5VskICPhQg',
    appId: '1:1062952966879:android:5ef04e1f4e9afc3d06a76a',
    messagingSenderId: '1062952966879',
    projectId: 'shamilapp-shamiltechnologies',
    databaseURL: 'https://shamilapp-shamiltechnologies-default-rtdb.firebaseio.com',
    storageBucket: 'shamilapp-shamiltechnologies.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo-5hmPwzGTbgvdXLWZkYJ1eh0ydo3dp0',
    appId: '1:1062952966879:ios:8dcd3f55023875a006a76a',
    messagingSenderId: '1062952966879',
    projectId: 'shamilapp-shamiltechnologies',
    databaseURL: 'https://shamilapp-shamiltechnologies-default-rtdb.firebaseio.com',
    storageBucket: 'shamilapp-shamiltechnologies.firebasestorage.app',
    iosBundleId: 'com.example.shamilMobileApp',
  );

}